let modalId=$('#image-gallery');$(document).ready(function(){loadGallery(!0,'a.thumbnail');function disableButtons(counter_max,counter_current){$('#show-previous-image, #show-next-image').show();if(counter_max===counter_current){$('#show-next-image').hide()}else if(counter_current===1){$('#show-previous-image').hide()}}
function loadGallery(setIDs,setClickAttr){let current_image,selector,counter=0;$('#show-next-image, #show-previous-image').click(function(){if($(this).attr('id')==='show-previous-image'){current_image--}else{current_image++}
selector=$('[data-image-id="'+current_image+'"]');updateGallery(selector)});function updateGallery(selector){let $sel=selector;current_image=$sel.data('image-id');$('#image-gallery-title').text($sel.data('title'));$('#image-gallery-image').attr('src',$sel.data('image'));disableButtons(counter,$sel.data('image-id'))}
if(setIDs==!0){$('[data-image-id]').each(function(){counter++;$(this).attr('data-image-id',counter)})}
$(setClickAttr).on('click',function(){updateGallery($(this))})}});$(document).keydown(function(e){switch(e.which){case 37:if((modalId.data('bs.modal')||{})._isShown&&$('#show-previous-image').is(":visible")){$('#show-previous-image').click()}
break;case 39:if((modalId.data('bs.modal')||{})._isShown&&$('#show-next-image').is(":visible")){$('#show-next-image').click()}
break;default:return}
e.preventDefault()});document.getElementById('list-city-1').onclick=function(){document.getElementById('feedback-form').style.display='none'};document.getElementById('list-city-2').onclick=function(){document.getElementById('feedback-form').style.display='none'};document.getElementById('close-1').onclick=function(){document.getElementById('feedback-form').style.display='block'};document.getElementById('close-2').onclick=function(){document.getElementById('feedback-form').style.display='block'};document.getElementById('close-3').onclick=function(){document.getElementById('feedback-form').style.display='block'};document.getElementById('close-appform').onclick=function(){document.getElementsByClassName('modal-backdrop').style.position='static'};if(window.matchMedia("(max-width: 576px)").matches){document.getElementById('close-appform').onclick=function(){document.getElementById('modal-mob').style.display='none'}}
if(window.matchMedia("(max-width: 414px)").matches){document.getElementById('list-city-2').onclick=function(){document.getElementById('logo-2').style.display='none'}}
if(document.getElementById('modal-form').style.display='none'){document.getElementById('logo').style.display='block'}